package com.librio.exception;

public enum BorrowErrorCode {
    RESOURCE_NOT_FOUND,
    REQUEST_NOT_FOUND,
    NO_PHYSICAL_COPY,
    NO_AVAILABLE_COPY,
    DUPLICATE_ACTIVE_REQUEST,
    ACTIVE_BORROWING_EXISTS,
    BORROWING_LIMIT_REACHED,
    INVALID_REQUEST_STATE,
    REQUEST_NOT_CANCELLABLE,
    REQUEST_EXPIRED,
    READER_INELIGIBLE,
    ITEM_MISMATCH,
    RESERVATION_CONFLICT,
    VALIDATION_ERROR,
    AUTHENTICATION_REQUIRED,
    OPERATION_FORBIDDEN,
    INVALID_CREDENTIALS,
    CSRF_TOKEN_INVALID,
    BORROWING_NOT_FOUND,
    BORROWING_ALREADY_RETURNED,
    BORROWING_ITEM_CONFLICT,
    DIGITAL_CONTENT_NOT_FOUND,
    RESOURCE_IN_USE
}
