DROP TABLE IF EXISTS borrowing CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS digital_item CASCADE;
DROP TABLE IF EXISTS physical_item CASCADE;
DROP TABLE IF EXISTS resource CASCADE;

CREATE TABLE resource (
                          id BIGINT PRIMARY KEY,
                          title VARCHAR(255) NOT NULL,
                          authors VARCHAR(255) NOT NULL,
                          description TEXT
);

CREATE TABLE physical_item (
                               id BIGINT PRIMARY KEY,
                               resource_id BIGINT NOT NULL,
                               status VARCHAR(32) NOT NULL,
                               CONSTRAINT fk_physical_resource
                                   FOREIGN KEY (resource_id)
                                       REFERENCES resource(id)
                                       ON DELETE CASCADE
);

CREATE TABLE digital_item (
                              id BIGINT PRIMARY KEY,
                              resource_id BIGINT NOT NULL UNIQUE,
                              CONSTRAINT fk_digital_resource
                                  FOREIGN KEY (resource_id)
                                      REFERENCES resource(id)
                                      ON DELETE CASCADE
);

CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL,
                          display_name VARCHAR(255),
                          role VARCHAR(32) NOT NULL,
                          account_status VARCHAR(32) NOT NULL,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL
);

CREATE TABLE borrowing (
                           id BIGINT PRIMARY KEY,
                           physical_item_id BIGINT NOT NULL,
                           reader_id BIGINT NOT NULL,
                           borrowed_at TIMESTAMP NOT NULL,
                           due_at TIMESTAMP NOT NULL,
                           returned_at TIMESTAMP,

                           CONSTRAINT fk_borrowing_physical
                               FOREIGN KEY (physical_item_id)
                                   REFERENCES physical_item(id),

                           CONSTRAINT fk_borrowing_reader
                               FOREIGN KEY (reader_id)
                                   REFERENCES accounts(id)
);