DROP TABLE IF EXISTS borrowing CASCADE;
DROP TABLE IF EXISTS borrow_request CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS digital_item CASCADE;
DROP TABLE IF EXISTS physical_item CASCADE;
DROP TABLE IF EXISTS resource CASCADE;

CREATE TABLE resource (
                          id BIGINT PRIMARY KEY,
                          title VARCHAR(255) NOT NULL,
                          authors VARCHAR(255) NOT NULL,
                          description TEXT
);

CREATE TABLE physical_item (
                               id BIGINT PRIMARY KEY,
                               resource_id BIGINT NOT NULL,
                               status VARCHAR(32) NOT NULL,
                               CONSTRAINT fk_physical_resource
                                   FOREIGN KEY (resource_id)
                                       REFERENCES resource(id)
                                       ON DELETE CASCADE
);

CREATE TABLE digital_item (
                              id BIGINT PRIMARY KEY,
                              resource_id BIGINT NOT NULL UNIQUE,
                              CONSTRAINT fk_digital_resource
                                  FOREIGN KEY (resource_id)
                                      REFERENCES resource(id)
                                      ON DELETE CASCADE
);

CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL,
                          display_name VARCHAR(255),
                          role VARCHAR(32) NOT NULL,
                          account_status VARCHAR(32) NOT NULL,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL
);

CREATE TABLE borrow_request (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                reader_id BIGINT NOT NULL,
                                resource_id BIGINT NOT NULL,
                                physical_item_id BIGINT,

                                status VARCHAR(32) NOT NULL,

                                requested_at TIMESTAMP NOT NULL,
                                status_updated_at TIMESTAMP NOT NULL,
                                expires_at TIMESTAMP,

                                prepared_at TIMESTAMP,
                                prepared_by BIGINT,

                                rejected_at TIMESTAMP,
                                rejected_by BIGINT,
                                rejection_reason VARCHAR(500),

                                fulfilled_at TIMESTAMP,
                                fulfilled_by BIGINT,

                                created_at TIMESTAMP NOT NULL,
                                updated_at TIMESTAMP NOT NULL,

                                CONSTRAINT fk_borrow_request_reader
                                    FOREIGN KEY (reader_id)
                                        REFERENCES accounts(id),

                                CONSTRAINT fk_borrow_request_resource
                                    FOREIGN KEY (resource_id)
                                        REFERENCES resource(id),

                                CONSTRAINT fk_borrow_request_item
                                    FOREIGN KEY (physical_item_id)
                                        REFERENCES physical_item(id),

                                CONSTRAINT fk_borrow_request_prepared_by
                                    FOREIGN KEY (prepared_by)
                                        REFERENCES accounts(id),

                                CONSTRAINT fk_borrow_request_rejected_by
                                    FOREIGN KEY (rejected_by)
                                        REFERENCES accounts(id),

                                CONSTRAINT fk_borrow_request_fulfilled_by
                                    FOREIGN KEY (fulfilled_by)
                                        REFERENCES accounts(id),

                                CONSTRAINT chk_borrow_request_status
                                    CHECK (status IN (
                                                      'REQUESTED',
                                                      'READY_FOR_PICKUP',
                                                      'FULFILLED',
                                                      'CANCELLED',
                                                      'REJECTED',
                                                      'EXPIRED'
                                        ))
);

CREATE TABLE borrowing (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           physical_item_id BIGINT NOT NULL,
                           reader_id BIGINT NOT NULL,
                           borrow_request_id BIGINT NOT NULL UNIQUE,

                           borrowed_at TIMESTAMP NOT NULL,
                           due_at TIMESTAMP NOT NULL,
                           returned_at TIMESTAMP,

                           CONSTRAINT fk_borrowing_physical
                               FOREIGN KEY (physical_item_id)
                                   REFERENCES physical_item(id),

                           CONSTRAINT fk_borrowing_reader
                               FOREIGN KEY (reader_id)
                                   REFERENCES accounts(id),

                           CONSTRAINT fk_borrowing_request
                               FOREIGN KEY (borrow_request_id)
                                   REFERENCES borrow_request(id)
);


CREATE UNIQUE INDEX uq_active_request_physical_item
    ON borrow_request (physical_item_id)
    WHERE status IN ('REQUESTED', 'READY_FOR_PICKUP');


CREATE UNIQUE INDEX uq_active_request_reader_resource
    ON borrow_request (reader_id, resource_id)
    WHERE status IN ('REQUESTED', 'READY_FOR_PICKUP');


CREATE INDEX idx_borrow_request_reader
    ON borrow_request (reader_id);

CREATE INDEX idx_borrow_request_resource
    ON borrow_request (resource_id);


CREATE INDEX idx_borrow_request_status
    ON borrow_request (status);